# -----------------------------
# Import sorting: isort
# -----------------------------
[tool.isort]
profile = "black"
line_length = 88
skip_glob = ["*.ipynb"]

# -----------------------------
# Linting & Docstrings: Ruff
# -----------------------------
[tool.ruff]
line-length = 88
extend-exclude = ["*.ipynb"]  # skip notebooks

[tool.ruff.lint]
# Enable general linting + docstring checks
select = ["E", "F", "I", "D"]
# Enforce NumPy-style docstrings
pydocstyle.convention = "numpy"

# -----------------------------
# Type checking: mypy
# -----------------------------
[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true

# Ignore all mypy errors inside the tests package so tests don't need annotations.
[[tool.mypy.overrides]]
module = ["tests.*"]
ignore_errors = true

[tool.setuptools.package-data]
"dolphindes" = ["py.typed"]
